In [1]:
import pandas as pd

In [8]:
pd.read_csv('../src/mt_rainier_stations.txt', skiprows = 3, sep = '|', header = None)

,0,1,2,3,4,5,6,7
0,CC,ARAT,46.789000,-121.853000,1822.440,Mount Ararat,2020-08-06T00:00:00,2599-12-31T23:59:59
1,CC,CARB,46.988320,-122.005410,872.470,Carbon Repeater,2018-10-16T00:00:00,2599-12-31T23:59:59
2,CC,COPP,46.797980,-121.828750,1895.000,COPP,2022-09-20T11:00:00,2599-12-31T23:59:59
3,CC,CRBN,46.988155,-121.961026,500.080,Carbon River Ranger Station,2020-10-22T00:00:00,2599-12-31T23:59:59
4,CC,CRYS,46.934410,-121.500260,2027.150,Crystal Mountain,2025-09-11T00:00:00,2599-12-31T23:59:59
5,CC,GNOB,46.794140,-121.914380,1659.360,Gobblers Knob Seismic,2022-10-18T13:21:00,2599-12-31T23:59:59
6,CC,GOBB,46.794140,-121.914380,1659.360,Gobbler's Knob,2022-09-07T00:00:00,2599-12-31T23:59:59
7,CC,GTWY,46.740208,-121.916966,617.235,Gateway Entrance Station,2020-10-28T20:00:00,2599-12-31T23:59:59
8,CC,KAUT,46.730263,-121.857381,689.000,Kautz Creek Helibase,2020-09-02T00:00:00,2599-12-31T23:59:59
9,CC,KAVK,46.760410,-122.038560,532.000,Kavik - Ashford Fire Station,2023-08-22T00:00:00,2599-12-31T23:59:59
10,CC,LONE,47.009890,-121.673690,1639.530,Lonesome Lake,2025-09-08T00:00:00,2599-12-31T23:59:59
11,CC,LONR,47.009890,-121.673690,1639.530,Lonesome Lake Unique,2025-10-02T16:30:00,2599-12-31T23:59:59
12,CC,MILD,46.808100,-121.775680,2015.590,Mildred Point,2022-09-20T00:00:00,2599-12-31T23:59:59
13,CC,OBSR,46.899719,-121.815331,2382.000,Observation Rock,2008-09-10T00:00:00,2599-12-31T23:59:59
14,CC,OPCH,46.731288,-121.571300,593.430,Ohanapecosh Administrative Area,2020-10-26T00:00:00,2599-12-31T23:59:59
15,CC,PANH,46.859032,-121.642592,2086.000,Panhandle Gap,2007-09-10T00:00:00,2599-12-31T23:59:59
16,CC,PARA,46.786441,-121.742195,1651.180,Paradise Precip Tower,2020-10-07T00:00:00,2599-12-31T23:59:59
17,CC,PR01,46.910103,-122.037586,648.000,Puyallup River 01,2016-11-03T00:00:00,2599-12-31T23:59:59
18,CC,PR02,46.918303,-122.048695,461.000,Puyallup River 02,2016-11-17T00:00:00,2599-12-31T23:59:59
19,CC,PR03,46.903433,-122.032691,523.000,Puyallup River 03,2016-09-15T00:00:00,2599-12-31T23:59:59
20,CC,PR04,46.929773,-121.988592,908.000,Puyallup River 04,2017-01-01T00:00:00,2599-12-31T23:59:59
21,CC,PR05,46.841723,-121.948863,1553.000,Puyallup River 05,2017-09-28T00:00:00,2599-12-31T23:59:59
22,CC,RUSH,46.903050,-121.944190,1235.000,Rushingwater Creek,2019-06-20T00:00:00,2599-12-31T23:59:59
23,CC,SIFT,46.866830,-121.953290,732.000,Swift Creek,2019-06-20T00:00:00,2599-12-31T23:59:59
24,CC,TABR,46.804350,-121.849480,1278.180,Tahoma Bridge,2022-09-26T00:00:00,2599-12-31T23:59:59
25,CC,TACK,46.803340,-121.844360,1357.110,Tahoma Creek Temporary Infrasound,2025-07-15T00:00:00,2025-08-30T00:00:00
26,CC,TAVI,46.795700,-121.884230,1054.650,Tahoma Vista,2022-09-26T00:00:00,2599-12-31T23:59:59
27,CC,VOIT,46.966360,-121.983280,977.150,Voight Creek,2019-09-25T00:00:00,2599-12-31T23:59:59
28,CC,WOW,46.780030,-121.885100,875.450,Mount Wow,2022-09-27T00:00:00,2599-12-31T23:59:59
29,UW,FMW,46.941914,-121.671465,1897.000,"Mt. Fremont, WA, USA",1972-08-31T00:00:00,2599-12-31T23:59:59
30,UW,LO2,46.750600,-121.809600,853.000,"Longmire, WA, USA",1980-01-01T00:00:00,2599-12-31T23:59:59
31,UW,LON,46.750599,-121.809601,853.000,"Longmire, WA, USA",1964-03-30T00:00:00,2599-12-31T23:59:59
32,UW,RCM,46.835570,-121.733180,3077.000,"Camp Muir, Mount Rainier, WA, USA",1993-09-09T00:00:00,2599-12-31T23:59:59
33,UW,RCS,46.870830,-121.732310,2877.000,"Mt. Rainier, Camp Schurman, WA, USA",1989-06-27T00:00:00,2599-12-31T23:59:59
34,UW,RER,46.818580,-121.842500,1751.100,"Emerald Ridge, Mount Rainier, WA, USA",1989-07-13T00:00:00,2599-12-31T23:59:59
35,UW,STAR,46.850849,-121.792953,3365.000,"St. Andrews Rock, Mt. Rainier, WA",2008-09-15T00:00:00,2599-12-31T23:59:59

In [11]:
"""
Fetch seismic channel types (BH/HH/EH/etc.) for each station
from the IRIS FDSN web service.

Requirements: pip install requests pandas obspy
Run: python fetch_station_channels.py
"""

import requests
import pandas as pd
from collections import defaultdict

# ── Station list ────────────────────────────────────────────────────────────
stations = [
    ("CC", "ARAT"), ("CC", "CARB"), ("CC", "COPP"), ("CC", "CRBN"), ("CC", "CRYS"),
    ("CC", "GNOB"), ("CC", "GOBB"), ("CC", "GTWY"), ("CC", "KAUT"), ("CC", "KAVK"),
    ("CC", "LONE"), ("CC", "LONR"), ("CC", "MILD"), ("CC", "OBSR"), ("CC", "OPCH"),
    ("CC", "PANH"), ("CC", "PARA"), ("CC", "PR01"), ("CC", "PR02"), ("CC", "PR03"),
    ("CC", "PR04"), ("CC", "PR05"), ("CC", "RUSH"), ("CC", "SIFT"), ("CC", "TABR"),
    ("CC", "TACK"), ("CC", "TAVI"), ("CC", "VOIT"), ("CC", "WOW"),
    ("UW", "FMW"),  ("UW", "LO2"),  ("UW", "LON"),  ("UW", "RCM"),
    ("UW", "RCS"),  ("UW", "RER"),  ("UW", "STAR"),
]

FDSN_URL = "https://service.iris.edu/fdsnws/station/1/query"

# ── Fetch channel data ───────────────────────────────────────────────────────
records = []
networks = defaultdict(list)
for net, sta in stations:
    networks[net].append(sta)

for net, sta_list in networks.items():
    params = {
        "network": net,
        "station": ",".join(sta_list),
        "level": "channel",
        "format": "text",
        "nodata": "404",
    }
    print(f"Querying network={net} ...")
    resp = requests.get(FDSN_URL, params=params, timeout=30)

    if resp.status_code != 200:
        print(f"  ⚠ HTTP {resp.status_code} for network {net}")
        continue

    for line in resp.text.strip().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("|")
        if len(parts) < 5:
            continue
        records.append({
            "Network":    parts[0].strip(),
            "Station":    parts[1].strip(),
            "Location":   parts[2].strip(),
            "Channel":    parts[3].strip(),
            "SampleRate": parts[14].strip() if len(parts) > 14 else "",
            "StartTime":  parts[15].strip() if len(parts) > 15 else "",
            "EndTime":    parts[16].strip() if len(parts) > 16 else "",
        })

df_channels = pd.DataFrame(records)
print(f"\nTotal channel records: {len(df_channels)}\n")

# ── Summarise by station ─────────────────────────────────────────────────────
summary = []
for (net, sta), grp in df_channels.groupby(["Network", "Station"]):
    channels      = sorted(grp["Channel"].unique())
    band_types    = sorted(set(ch[:2] for ch in channels))   # e.g. BH, HH, EH
    summary.append({
        "Network":      net,
        "Station":      sta,
        "Band_Types":   ", ".join(band_types),        # compact view
        "All_Channels": ", ".join(channels),           # full list
        "Num_Channels": len(channels),
    })

df_summary = pd.DataFrame(summary)

# ── Print & save ─────────────────────────────────────────────────────────────
print("=== Channel Summary by Station ===")
print(df_summary.to_string(index=False))

df_summary.to_csv("station_channel_summary.csv", index=False)
df_channels.to_csv("station_channels_detail.csv", index=False)
print("\nSaved: station_channel_summary.csv  |  station_channels_detail.csv")

Querying network=CC ...
Querying network=UW ...

Total channel records: 847

=== Channel Summary by Station ===
Network Station                                                                                         Band_Types                                                                                                                                                                                                                                   All_Channels  Num_Channels
     CC    ARAT                                                                                 BD, BH, CD, CH, HD                                                                                                                                                                                                    BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ, HDF             9
     CC    CARB                                                                                             BH, CH                                                                                                                                                                                                                   BHE, BHN, BHZ, CHE, CHN, CHZ             6
     CC    COPP                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    CRBN                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    CRYS                                                                                     CD, CH, HD, HH                                                                                                                                                                                                         CDF, CHE, CHN, CHZ, HDF, HHE, HHN, HHZ             8
     CC    GNOB                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    GOBB                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    GTWY                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    KAUT                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    KAVK                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    LONE                                                                                             BD, BH                                                                                                                                                                                                                             BDF, BHE, BHN, BHZ             4
     CC    LONR                                                                                             BD, BH                                                                                                                                                                                                                             BDF, BHE, BHN, BHZ             4
     CC    MILD                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    OBSR                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    OPCH                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    PANH                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    PARA                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    PR01                                                                                             BD, BH                                                                                                                                                                                                                             BDF, BHE, BHN, BHZ             4
     CC    PR02                                                                                             BD, BH                                                                                                                                                                                                                             BDF, BHE, BHN, BHZ             4
     CC    PR03                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    PR04                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    PR05                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    RUSH                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC    SIFT                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    TABR                                                                                 BD, BH, CD, CH, HD                                                                                                                                                                                                    BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ, HDF             9
     CC    TACK                                                                                                 HD                                                                                                                                                                                                                                            HDF             1
     CC    TAVI                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     CC    VOIT                                                                                                 BH                                                                                                                                                                                                                                  BHE, BHN, BHZ             3
     CC     WOW                                                                                     BD, BH, CD, CH                                                                                                                                                                                                         BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ             8
     UW     FMW                                         EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP                                                                                                                                   EHZ, GAN, GEL, GLA, GLO, GNS, GPL, GST, HHE, HHN, HHZ, LCE, LCQ, SHZ, VCO, VDT, VEC, VEI, VM1, VM2, VM3, VPB            22
     UW     LO2                                                                                             EH, SH                                                                                                                                                                                                                                       EHZ, SHZ             2
     UW     LON BH, EH, EN, HH, LC, LO, OC, SB, SC, SD, SH, SI, SM, SN, SP, SR, SS, ST, SW, VA, VC, VE, VF, VK, VM BHE, BHN, BHZ, EHZ, ENE, ENN, ENZ, HHE, HHN, HHZ, LCE, LCL, LCQ, LOG, OCF, SBT, SCA, SCE, SCK, SCS, SCT, SDG, SDL, SDT, SHZ, SIO, SMD, SNE, SNI, SNN, SNZ, SPK, SPO, SRD, SSL, SSQ, STH, SWR, VAP, VCO, VEA, VEC, VEP, VFP, VKI, VM1, VM2, VM3            48
     UW     RCM                                         EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP                                                                                                               EH1, EH2, EHE, EHN, EHZ, GAN, GEL, GLA, GLO, GNS, GPL, GST, HHE, HHN, HHZ, LCE, LCQ, SHZ, VCO, VDT, VEC, VEI, VM1, VM2, VM3, VPB            26
     UW     RCS                                                                                             EH, SH                                                                                                                                                                                                                                       EHZ, SHZ             2
     UW     RER                                     BD, EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP                                                                                                                              BDF, EHZ, GAN, GEL, GLA, GLO, GNS, GPL, GST, HHE, HHN, HHZ, LCE, LCQ, SHZ, VCO, VDT, VEC, VEI, VM1, VM2, VM3, VPB            23
     UW    STAR                                                                                             EH, EL                                                                                                                                                                                                                             EHE, EHN, EHZ, ELZ             4

Saved: station_channel_summary.csv  |  station_channels_detail.csv

In [12]:
df_summary

,Network,Station,Band_Types,All_Channels,Num_Channels
0,CC,ARAT,"BD, BH, CD, CH, HD","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ, HDF",9
1,CC,CARB,"BH, CH","BHE, BHN, BHZ, CHE, CHN, CHZ",6
2,CC,COPP,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
3,CC,CRBN,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
4,CC,CRYS,"CD, CH, HD, HH","CDF, CHE, CHN, CHZ, HDF, HHE, HHN, HHZ",8
5,CC,GNOB,BH,"BHE, BHN, BHZ",3
6,CC,GOBB,BH,"BHE, BHN, BHZ",3
7,CC,GTWY,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
8,CC,KAUT,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
9,CC,KAVK,BH,"BHE, BHN, BHZ",3
10,CC,LONE,"BD, BH","BDF, BHE, BHN, BHZ",4
11,CC,LONR,"BD, BH","BDF, BHE, BHN, BHZ",4
12,CC,MILD,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
13,CC,OBSR,BH,"BHE, BHN, BHZ",3
14,CC,OPCH,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
15,CC,PANH,BH,"BHE, BHN, BHZ",3
16,CC,PARA,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
17,CC,PR01,"BD, BH","BDF, BHE, BHN, BHZ",4
18,CC,PR02,"BD, BH","BDF, BHE, BHN, BHZ",4
19,CC,PR03,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
20,CC,PR04,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
21,CC,PR05,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
22,CC,RUSH,BH,"BHE, BHN, BHZ",3
23,CC,SIFT,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
24,CC,TABR,"BD, BH, CD, CH, HD","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ, HDF",9
25,CC,TACK,HD,HDF,1
26,CC,TAVI,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
27,CC,VOIT,BH,"BHE, BHN, BHZ",3
28,CC,WOW,"BD, BH, CD, CH","BDF, BHE, BHN, BHZ, CDF, CHE, CHN, CHZ",8
29,UW,FMW,"EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD...","EHZ, GAN, GEL, GLA, GLO, GNS, GPL, GST, HHE, H...",22
30,UW,LO2,"EH, SH","EHZ, SHZ",2
31,UW,LON,"BH, EH, EN, HH, LC, LO, OC, SB, SC, SD, SH, SI...","BHE, BHN, BHZ, EHZ, ENE, ENN, ENZ, HHE, HHN, H...",48
32,UW,RCM,"EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD...","EH1, EH2, EHE, EHN, EHZ, GAN, GEL, GLA, GLO, G...",26
33,UW,RCS,"EH, SH","EHZ, SHZ",2
34,UW,RER,"BD, EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC...","BDF, EHZ, GAN, GEL, GLA, GLO, GNS, GPL, GST, H...",23
35,UW,STAR,"EH, EL","EHE, EHN, EHZ, ELZ",4

In [13]:
def select_preferred_channels(df_summary):
    """
    For each station, select channels by priority: BH > HH > EH.
    Returns a new dataframe with a 'Selected_Band' and 'Selected_Channels' column.
    """
    PRIORITY = ["BH", "HH", "EH"]
    
    results = []
    for _, row in df_summary.iterrows():
        available_bands = [b.strip() for b in row["Band_Types"].split(",")]
        
        selected = None
        for band in PRIORITY:
            if band in available_bands:
                selected = band
                break
        
        # Filter All_Channels to only the selected band
        if selected:
            selected_channels = [
                ch for ch in row["All_Channels"].split(", ")
                if ch.startswith(selected)
            ]
        else:
            selected_channels = []  # None of BH/HH/EH available

        results.append({
            "Network":           row["Network"],
            "Station":           row["Station"],
            "Available_Bands":   row["Band_Types"],
            "Selected_Band":     selected if selected else "NONE",
            "Selected_Channels": ", ".join(selected_channels),
        })
    
    return pd.DataFrame(results)

df_preferred = select_preferred_channels(df_summary)
print(df_preferred.to_string(index=False))
df_preferred.to_csv("station_preferred_channels.csv", index=False)

Network Station                                                                                    Available_Bands Selected_Band Selected_Channels
     CC    ARAT                                                                                 BD, BH, CD, CH, HD            BH     BHE, BHN, BHZ
     CC    CARB                                                                                             BH, CH            BH     BHE, BHN, BHZ
     CC    COPP                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    CRBN                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    CRYS                                                                                     CD, CH, HD, HH            HH     HHE, HHN, HHZ
     CC    GNOB                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    GOBB                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    GTWY                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    KAUT                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    KAVK                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    LONE                                                                                             BD, BH            BH     BHE, BHN, BHZ
     CC    LONR                                                                                             BD, BH            BH     BHE, BHN, BHZ
     CC    MILD                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    OBSR                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    OPCH                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    PANH                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    PARA                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    PR01                                                                                             BD, BH            BH     BHE, BHN, BHZ
     CC    PR02                                                                                             BD, BH            BH     BHE, BHN, BHZ
     CC    PR03                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    PR04                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    PR05                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    RUSH                                                                                                 BH            BH     BHE, BHN, BHZ
     CC    SIFT                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    TABR                                                                                 BD, BH, CD, CH, HD            BH     BHE, BHN, BHZ
     CC    TACK                                                                                                 HD          NONE
     CC    TAVI                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     CC    VOIT                                                                                                 BH            BH     BHE, BHN, BHZ
     CC     WOW                                                                                     BD, BH, CD, CH            BH     BHE, BHN, BHZ
     UW     FMW                                         EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP            HH     HHE, HHN, HHZ
     UW     LO2                                                                                             EH, SH            EH               EHZ
     UW     LON BH, EH, EN, HH, LC, LO, OC, SB, SC, SD, SH, SI, SM, SN, SP, SR, SS, ST, SW, VA, VC, VE, VF, VK, VM            BH     BHE, BHN, BHZ
     UW     RCM                                         EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP            HH     HHE, HHN, HHZ
     UW     RCS                                                                                             EH, SH            EH               EHZ
     UW     RER                                     BD, EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD, VE, VM, VP            HH     HHE, HHN, HHZ
     UW    STAR                                                                                             EH, EL            EH     EHE, EHN, EHZ

In [14]:
df_preferred

,Network,Station,Available_Bands,Selected_Band,Selected_Channels
0,CC,ARAT,"BD, BH, CD, CH, HD",BH,"BHE, BHN, BHZ"
1,CC,CARB,"BH, CH",BH,"BHE, BHN, BHZ"
2,CC,COPP,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
3,CC,CRBN,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
4,CC,CRYS,"CD, CH, HD, HH",HH,"HHE, HHN, HHZ"
5,CC,GNOB,BH,BH,"BHE, BHN, BHZ"
6,CC,GOBB,BH,BH,"BHE, BHN, BHZ"
7,CC,GTWY,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
8,CC,KAUT,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
9,CC,KAVK,BH,BH,"BHE, BHN, BHZ"
10,CC,LONE,"BD, BH",BH,"BHE, BHN, BHZ"
11,CC,LONR,"BD, BH",BH,"BHE, BHN, BHZ"
12,CC,MILD,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
13,CC,OBSR,BH,BH,"BHE, BHN, BHZ"
14,CC,OPCH,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
15,CC,PANH,BH,BH,"BHE, BHN, BHZ"
16,CC,PARA,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
17,CC,PR01,"BD, BH",BH,"BHE, BHN, BHZ"
18,CC,PR02,"BD, BH",BH,"BHE, BHN, BHZ"
19,CC,PR03,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
20,CC,PR04,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
21,CC,PR05,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
22,CC,RUSH,BH,BH,"BHE, BHN, BHZ"
23,CC,SIFT,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
24,CC,TABR,"BD, BH, CD, CH, HD",BH,"BHE, BHN, BHZ"
25,CC,TACK,HD,NONE,
26,CC,TAVI,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
27,CC,VOIT,BH,BH,"BHE, BHN, BHZ"
28,CC,WOW,"BD, BH, CD, CH",BH,"BHE, BHN, BHZ"
29,UW,FMW,"EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD...",HH,"HHE, HHN, HHZ"
30,UW,LO2,"EH, SH",EH,EHZ
31,UW,LON,"BH, EH, EN, HH, LC, LO, OC, SB, SC, SD, SH, SI...",BH,"BHE, BHN, BHZ"
32,UW,RCM,"EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC, VD...",HH,"HHE, HHN, HHZ"
33,UW,RCS,"EH, SH",EH,EHZ
34,UW,RER,"BD, EH, GA, GE, GL, GN, GP, GS, HH, LC, SH, VC...",HH,"HHE, HHN, HHZ"
35,UW,STAR,"EH, EL",EH,"EHE, EHN, EHZ"

In [15]:
import json

entries = (
    df_preferred[df_preferred["Selected_Band"] != "NONE"]
    [["Network", "Station", "Selected_Band"]]
    .rename(columns={"Network": "net", "Station": "sta", "Selected_Band": "chn"})
    .to_dict(orient="records")
)

print(json.dumps(entries, indent=2))

# Save to file
with open("../src/mt_rainier_stations.json", "w") as f:
    json.dump(entries, f, indent=2)

[
  {
    "net": "CC",
    "sta": "ARAT",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "CARB",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "COPP",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "CRBN",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "CRYS",
    "chn": "HH"
  },
  {
    "net": "CC",
    "sta": "GNOB",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "GOBB",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "GTWY",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "KAUT",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "KAVK",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "LONE",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "LONR",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "MILD",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "OBSR",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "OPCH",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PANH",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PARA",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PR01",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PR02",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PR03",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PR04",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "PR05",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "RUSH",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "SIFT",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "TABR",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "TAVI",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "VOIT",
    "chn": "BH"
  },
  {
    "net": "CC",
    "sta": "WOW",
    "chn": "BH"
  },
  {
    "net": "UW",
    "sta": "FMW",
    "chn": "HH"
  },
  {
    "net": "UW",
    "sta": "LO2",
    "chn": "EH"
  },
  {
    "net": "UW",
    "sta": "LON",
    "chn": "BH"
  },
  {
    "net": "UW",
    "sta": "RCM",
    "chn": "HH"
  },
  {
    "net": "UW",
    "sta": "RCS",
    "chn": "EH"
  },
  {
    "net": "UW",
    "sta": "RER",
    "chn": "HH"
  },
  {
    "net": "UW",
    "sta": "STAR",
    "chn": "EH"
  }
]